# Path to my oh-my-zsh configuration
export ZSH=$HOME/.oh-my-zsh


# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(brew web-search)

# Load the shell dotfiles
for file in $HOME/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

ZSH_THEME=robbyrussell
source $ZSH/oh-my-zsh.sh

# Source local (private) settings specific to machine if it exists
[ -f ~/.zsh.local ] && source ~/.zsh.local
